
image: gitpod/workspace-full

tasks:
  - name: run server
    command: npx five-server --port=3000

  - name: install sass
    init: npm install sass --global

  - name: install neovim
    init: sudo apt install nvim

ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview
vscode:
  extensions:
    - asvetliakov.vscode-neovim